Vagrant.configure(2) do |config|
  config.vm.box = "chad-thompson/ubuntu-trusty64-gui"
  config.vm.provider "virtualbox" do |vb|
       vb.gui = true
       vb.memory = "1024"
       vb.name="Anson-esharma2-Viva"
       #Disable USB
       vb.customize ["modifyvm", :id, "--usb", "off"]
       vb.customize ["modifyvm", :id, "--usbehci", "off"]
    end
  config.vm.provision "shell", inline: <<-SHELL
    sudo add-apt-repository ppa:webupd8team/java
    sudo apt-get update -y
    echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
    sudo apt-get install -y oracle-java8-installer
  
    sudo apt-get -y install git
    #dconf write /org/gnome/desktop/screensaver/idle-activation-enabled false
   # dconf write /org/gnome/desktop/screensaver/lock-enabled false
     
    cd Desktop
    git clone https://github.com/SoftwareEngineeringToolDemos/ICSE-2014-Viva.git
    cd ICSE-2014-Viva/build-vm

sudo chmod +x commands.sh


    cp commands.sh /home/vagrant/Desktop/commands.sh
    cp Viva.desktop /home/vagrant/Desktop
    cp readme.txt /home/vagrant/Desktop
    cp license.txt /home/vagrant/Desktop
    cp installation.txt /home/vagrant/Desktop    
    cp ../Binary/viva.jar /home/vagrant/Desktop
    cp VivaAuthorDemonstration.desktop /home/vagrant/Desktop
    cp VivaDemoVideo.desktop /home/vagrant/Desktop
    
       
    sudo mkdir "/home/vagrant/.config/autostart"
    sudo cp Viva.desktop /home/vagrant/.config/autostart/Viva.desktop
       
    #Remove unused Launcher Applications
    sudo rm /usr/share/applications/ubuntu-amazon-default.desktop
    sudo rm /usr/share/applications/ubuntu-software-center.desktop
    sudo rm /usr/share/applications/libreoffice.desktop
    sudo rm /usr/share/applications/unity-control-center.desktop
    
    sudo reboot

   SHELL
end
