Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/ubuntu1404-desktop"
  config.vm.provider "virtualbox" do |vb|
       vb.gui = true
       vb.memory = "1024"
       vb.name="Anson-esharma2-Viva"
    end
  config.vm.provision "shell", inline: <<-SHELL
    sudo add-apt-repository ppa:webupd8team/java
    sudo apt-get update
    sudo apt-get install oracle-java8-installer
    sudo apt-get -y install git

    mkdir ~/Viva_dir
    git clone https://github.com/SoftwareEngineeringToolDemos/ICSE-2014-Viva.git
    cp ICSE-2013-Viva/build-vm/executable/* ~/Desktop/.
    
   SHELL
end
