Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/ubuntu1404-desktop"
  config.vm.provider "virtualbox" do |vb|
       vb.gui = true
       vb.memory = "1024"
       vb.name="Anson-esharma2-Viva"
       #Disable USB
       vb.customize ["modifyvm", :id, "--usb", "off"]
       vb.customize ["modifyvm", :id, "--usbehci", "off"]
    end
  config.vm.provision "shell", inline: <<-SHELL
    sudo add-apt-repository ppa:webupd8team/java
    sudo apt-get update -y
    echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
    sudo apt-get install -y oracle-java8-installer
  
    sudo apt-get install -y wget
    sudo apt-get -y install git
     
    git clone https://github.com/SoftwareEngineeringToolDemos/ICSE-2014-Viva.git
    cd ICSE-2014-Viva/build-vm
    sudo chmod +x commands.sh
    cp commands.sh ../../commands.sh 
    cp Viva.desktop ../../Viva.desktop
    cp Readme.txt ../../Readme.txt
    cp -r Licenses/ ../../Licenses
    cp Installation.txt ../../Installation.txt	
    cp -r ../Binary/ ../../VivaBinary/
    cp VivaAuthorDemonstration.desktop ../../VivaAuthorDemonstration.desktop
    cp VivaDemoVideo.desktop ../../VivaDemoVideo.desktop
    
    cd ../../
    tar xvzf RefDistillerWorkspace.tar.gz
    sudo mkdir "/home/vagrant/.config/autostart"
    sudo cp Viva.desktop /home/vagrant/.config/autostart/Viva.desktop
	
    #Remove unused Launcher Applications
    sudo rm -f "/usr/share/applications/ubuntu-amazon-default.desktop"
    sudo rm -f "/usr/share/applications/ubuntu-software-center.desktop"
    sudo reboot

   SHELL
end
